# Generated by Django 4.1.5 on 2023-02-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg',
        ),
    ]
