# Generated by Django 4.1.4 on 2022-12-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Phonenumber', models.BigIntegerField()),
                ('Place', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='id')),
                ('Workex', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='owvaddwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Sqft', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=80)),
                ('City', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=60)),
                ('Price', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='id')),
                ('Pincode', models.CharField(max_length=25)),
                ('Type', models.CharField(max_length=80)),
                ('Facility', models.CharField(max_length=50)),
                ('Capability', models.CharField(max_length=60)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner_tb')),
            ],
        ),
    ]
