# Generated by Django 4.1.4 on 2022-12-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_tb',
            name='Proof',
            field=models.ImageField(null='True', upload_to='id'),
            preserve_default='True',
        ),
    ]
