# Generated by Django 4.1.4 on 2023-01-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_owner_tb_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_tb',
            name='Proof',
            field=models.ImageField(null=True, upload_to='id'),
        ),
    ]
