# Generated by Django 4.1.4 on 2023-01-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_alter_owner_tb_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Phonenumber', models.BigIntegerField()),
                ('Workex', models.CharField(max_length=25)),
                ('Image', models.ImageField(upload_to='id')),
                ('Place', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=60)),
                ('Password', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner_tb')),
            ],
        ),
        migrations.CreateModel(
            name='Workassign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Phonenumber', models.BigIntegerField()),
                ('requestmssg', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner_tb')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.addtech')),
            ],
        ),
    ]
