# Generated by Django 4.1.5 on 2023-02-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_addtech_workassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_tb',
            name='accept',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='owner_tb',
            name='reject',
            field=models.BooleanField(default='False'),
        ),
    ]
