# Generated by Django 5.2.5 on 2026-08-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_owner_tb_accept_owner_tb_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtech',
            name='Email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='addtech',
            name='Password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='owner_tb',
            name='Email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='owner_tb',
            name='Password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='owner_tb',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='owner_tb',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
