# Generated by Django 4.1.4 on 2022-12-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=50)),
                ('Phonenumber', models.BigIntegerField()),
                ('Place', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
