# Generated by Django 4.1.4 on 2022-12-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_tb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tb',
            name='Image',
            field=models.ImageField(default=0, upload_to='id'),
            preserve_default=False,
        ),
    ]
