# Generated by Django 4.1.4 on 2023-01-12 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_alter_owner_tb_proof'),
        ('user', '0004_alter_user_tb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='no.jpg', upload_to='')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Sqft', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Capability', models.CharField(max_length=100)),
                ('Date_book', models.DateField(default=django.utils.timezone.now)),
                ('Checkout_status', models.BooleanField(default=False)),
                ('Status', models.BooleanField(default=False)),
                ('qty', models.IntegerField(default='1')),
                ('addwork', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='owners.owvaddwork')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner_tb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_tb')),
            ],
        ),
    ]
