# Generated by Django 4.1.4 on 2023-01-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_booking',
            name='qty',
        ),
        migrations.AddField(
            model_name='user_booking',
            name='nohrs',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
