# Generated by Django 4.1.4 on 2023-01-17 07:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_alter_owner_tb_proof'),
        ('user', '0006_remove_user_booking_qty_user_booking_nohrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WsName', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Date_book', models.DateField(default=django.utils.timezone.now)),
                ('Image', models.ImageField(null=True, upload_to='cart')),
                ('Status', models.BooleanField(default='False')),
                ('Paystatus', models.BooleanField(default='False')),
                ('nohrs', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner_tb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_tb')),
            ],
        ),
    ]
