# Generated by Django 3.2.11 on 2023-01-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_alter_owner_tb_proof'),
        ('user', '0009_alter_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='addwork',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='owners.owvaddwork'),
            preserve_default=False,
        ),
    ]
