# Generated by Django 3.2.11 on 2023-01-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_cart_addwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='addwork',
        ),
    ]
