# Generated by Django 4.1.4 on 2023-02-04 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_addtech_workassign'),
        ('user', '0013_messages_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='refund_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner_tb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_tb')),
            ],
        ),
    ]
