# Generated by Django 4.1.4 on 2023-02-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_refund_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund_tb',
            old_name='Name',
            new_name='refund_tb',
        ),
        migrations.RemoveField(
            model_name='refund_tb',
            name='Price',
        ),
    ]
