# Generated by Django 4.1.4 on 2023-02-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_refund_tb_refund_tb_name_cart_totalsum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund_tb',
            name='Name',
        ),
    ]
