# Generated by Django 4.1.4 on 2023-02-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_refund_tb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund_tb',
            name='Status',
            field=models.BooleanField(default='False'),
        ),
    ]
