# Generated by Django 4.1.4 on 2023-02-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_refund_tb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund_tb',
            name='sta',
            field=models.BooleanField(default='False'),
        ),
    ]
