# Generated by Django 4.1.4 on 2023-02-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_refund_tb_sta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund_tb',
            name='sta',
        ),
    ]
