# Generated by Django 5.2.5 on 2026-08-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_messages_tb_accept_remove_messages_tb_reject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Paystatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refund_tb',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request_tb',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request_tb',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_tb',
            name='Email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user_tb',
            name='Password',
            field=models.CharField(max_length=128),
        ),
    ]
