# Generated by Django 5.2.5 on 2026-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_cart_refundstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='RazorpayOrderId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='RazorpayPaymentId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='RazorpayRefundId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='RazorpaySignature',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
