# Generated by Django 4.1.4 on 2023-01-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Place', models.CharField(max_length=60)),
                ('Password', models.CharField(max_length=20)),
                ('Workex', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Phonenumber', models.BigIntegerField()),
                ('Password', models.CharField(max_length=20)),
                ('Workex', models.CharField(max_length=25)),
            ],
        ),
    ]
