# Generated by Django 5.2.5 on 2026-08-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0002_delete_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='Email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='Password',
            field=models.CharField(max_length=128),
        ),
    ]
