# Generated by Django 5.2.5 on 2026-08-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectadmin',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='projectadmin',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
