# Generated by Django 4.1.4 on 2022-12-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_tb_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tb',
            name='Image',
            field=models.ImageField(null=True, upload_to='id'),
        ),
    ]
