# Generated by Django 4.1.4 on 2023-01-30 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_alter_owner_tb_proof'),
        ('user', '0011_remove_cart_addwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.BigIntegerField()),
                ('Subject', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner_tb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_tb')),
            ],
        ),
        migrations.DeleteModel(
            name='user_booking',
        ),
    ]
