# Generated by Django 4.1.4 on 2023-02-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_name_refund_tb_refund_tb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund_tb',
            old_name='refund_tb',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='cart',
            name='totalsum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refund_tb',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
