# Generated by Django 4.1.4 on 2023-02-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_refund_tb_sta'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund_tb',
            name='accept',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='refund_tb',
            name='reject',
            field=models.BooleanField(default='False'),
        ),
    ]
