# Generated by Django 4.1.4 on 2023-02-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_refund_tb_accept_refund_tb_reject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund_tb',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='refund_tb',
            name='reject',
        ),
        migrations.AddField(
            model_name='messages_tb',
            name='accept',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='messages_tb',
            name='reject',
            field=models.BooleanField(default='False'),
        ),
    ]
