# Generated by Django 5.2.5 on 2026-08-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_hash_existing_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Refundstatus',
            field=models.BooleanField(default=False),
        ),
    ]
